apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-namespace
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pradeepch82/tea:1.1
        ports:
        - containerPort: 80
